# Generated by Django 4.0.3 on 2022-04-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uylar',
            options={'verbose_name': 'Uylar', 'verbose_name_plural': 'Uylar'},
        ),
        migrations.AlterField(
            model_name='uylar',
            name='Aftoturargox',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Aftoturargox'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bino_asosi',
            field=models.CharField(choices=[('1', "G'ishtli"), ('2', 'Panel')], default=1, max_length=100, verbose_name='Bino Asosi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bolalar_maydonchasi',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Bolalar Maydonchasi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='internet',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=5, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='kanalizatsiya',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Kanalizatsiya'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='lift',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name='Lift'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='qoriqlash',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name="Qo'riqlash"),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='uy_turi',
            field=models.CharField(choices=[('2', 'Sotuv'), ('1', 'Ijara')], default=1, max_length=100, verbose_name='Tanlang'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='video_kuzatuv',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Video Kuzatuv'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('11', 'Navoiy'), ('4', 'Andijon'), ('6', 'Buxoro'), ('8', 'Xorazm'), ('1', 'Toshkent Shahar'), ('2', 'Toshkent Viloyat'), ('12', "Qoraqalpog'iston"), ('3', "Farg'ona"), ('7', 'Samarqand'), ('5', 'Namangan'), ('10', 'Surxandaryo'), ('9', 'Qashqadaryo')], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('3', '3')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
