# Generated by Django 4.0.3 on 2022-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0003_alter_uylar_aftoturargox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='bino_asosi',
            field=models.CharField(choices=[('2', 'Panel'), ('1', "G'ishtli")], default=1, max_length=100, verbose_name='Bino Asosi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('4', 'Andijon'), ('12', "Qoraqalpog'iston"), ('11', 'Navoiy'), ('8', 'Xorazm'), ('10', 'Surxandaryo'), ('1', 'Toshkent Shahar'), ('6', 'Buxoro'), ('5', 'Namangan'), ('2', 'Toshkent Viloyat'), ('7', 'Samarqand'), ('9', 'Qashqadaryo'), ('3', "Farg'ona")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('6', '6'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
