# Generated by Django 4.0.3 on 2022-04-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uybor', '0004_alter_uylar_bino_asosi_alter_uylar_viloyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uylar',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Muxbiri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uylar',
            name='Aftoturargox',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Aftoturargox'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bolalar_maydonchasi',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Bolalar Maydonchasi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='internet',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=5, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='kanalizatsiya',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Kanalizatsiya'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='lift',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name='Lift'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='qoriqlash',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name="Qo'riqlash"),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='video_kuzatuv',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Video Kuzatuv'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('11', 'Navoiy'), ('2', 'Toshkent Viloyat'), ('10', 'Surxandaryo'), ('7', 'Samarqand'), ('6', 'Buxoro'), ('1', 'Toshkent Shahar'), ('9', 'Qashqadaryo'), ('12', "Qoraqalpog'iston"), ('4', 'Andijon'), ('8', 'Xorazm'), ('5', 'Namangan'), ('3', "Farg'ona")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('1', '1'), ('5', '5'), ('2', '2'), ('4', '4')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
