# Generated by Django 4.0.3 on 2022-04-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0007_alter_uylar_viloyat_alter_uylar_xonalar_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='uylar',
            name='xona_kattaligi',
            field=models.FloatField(default=1, verbose_name='Nech Metr Kvadrat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bino_asosi',
            field=models.CharField(choices=[('2', 'Panel'), ('1', "G'ishtli")], default=1, max_length=100, verbose_name='Bino Asosi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('7', 'Samarqand'), ('10', 'Surxandaryo'), ('11', 'Navoiy'), ('8', 'Xorazm'), ('12', "Qoraqalpog'iston"), ('1', 'Toshkent Shahar'), ('4', 'Andijon'), ('6', 'Buxoro'), ('3', "Farg'ona"), ('9', 'Qashqadaryo'), ('2', 'Toshkent Viloyat'), ('5', 'Namangan')], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('6', '6'), ('1', '1'), ('5', '5'), ('4', '4'), ('2', '2'), ('3', '3')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
