# Generated by Django 4.0.3 on 2022-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0008_uylar_xona_kattaligi_alter_uylar_bino_asosi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='uy_turi',
            field=models.CharField(choices=[('1', 'Ijara'), ('2', 'Sotuv')], default=1, max_length=100, verbose_name='Tanlang'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('10', 'Surxandaryo'), ('11', 'Navoiy'), ('8', 'Xorazm'), ('12', "Qoraqalpog'iston"), ('9', 'Qashqadaryo'), ('1', 'Toshkent Shahar'), ('6', 'Buxoro'), ('2', 'Toshkent Viloyat'), ('5', 'Namangan'), ('4', 'Andijon'), ('7', 'Samarqand'), ('3', "Farg'ona")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xona_kattaligi',
            field=models.FloatField(verbose_name='Nechi Metr Kvadrat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
