# Generated by Django 4.0.3 on 2022-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0009_alter_uylar_uy_turi_alter_uylar_viloyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='Aftoturargox',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Aftoturargox'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bolalar_maydonchasi',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Bolalar Maydonchasi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='internet',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=5, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='kanalizatsiya',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Kanalizatsiya'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='lift',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name='Lift'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='narxi',
            field=models.FloatField(verbose_name='Narxi -> $'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='qoriqlash',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name="Qo'riqlash"),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='video_kuzatuv',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Video Kuzatuv'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('10', 'Surxandaryo'), ('3', "Farg'ona"), ('7', 'Samarqand'), ('2', 'Toshkent Viloyat'), ('1', 'Toshkent Shahar'), ('8', 'Xorazm'), ('6', 'Buxoro'), ('4', 'Andijon'), ('9', 'Qashqadaryo'), ('11', 'Navoiy'), ('5', 'Namangan'), ('12', "Qoraqalpog'iston")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1'), ('6', '6')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
