# Generated by Django 4.0.3 on 2022-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0011_alter_uylar_aftoturargox_alter_uylar_bino_asosi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('8', 'Xorazm'), ('10', 'Surxandaryo'), ('5', 'Namangan'), ('4', 'Andijon'), ('1', 'Toshkent Shahar'), ('12', "Qoraqalpog'iston"), ('9', 'Qashqadaryo'), ('2', 'Toshkent Viloyat'), ('6', 'Buxoro'), ('11', 'Navoiy'), ('7', 'Samarqand'), ('3', "Farg'ona")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('5', '5'), ('1', '1'), ('6', '6'), ('4', '4'), ('2', '2'), ('3', '3')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
