# Generated by Django 4.0.3 on 2022-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0013_alter_uylar_aftoturargox_alter_uylar_bino_asosi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='bino_asosi',
            field=models.CharField(choices=[('1', "G'ishtli"), ('2', 'Panel')], default=1, max_length=100, verbose_name='Bino Asosi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('11', 'Navoiy'), ('4', 'Andijon'), ('2', 'Toshkent Viloyat'), ('9', 'Qashqadaryo'), ('7', 'Samarqand'), ('6', 'Buxoro'), ('1', 'Toshkent Shahar'), ('12', "Qoraqalpog'iston"), ('8', 'Xorazm'), ('10', 'Surxandaryo'), ('5', 'Namangan'), ('3', "Farg'ona")], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('2', '2'), ('3', '3'), ('1', '1'), ('5', '5')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
