# Generated by Django 4.0.3 on 2022-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0014_alter_uylar_bino_asosi_alter_uylar_viloyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('4', 'Andijon'), ('5', 'Namangan'), ('6', 'Buxoro'), ('1', 'Toshkent Shahar'), ('9', 'Qashqadaryo'), ('11', 'Navoiy'), ('10', 'Surxandaryo'), ('8', 'Xorazm'), ('2', 'Toshkent Viloyat'), ('3', "Farg'ona"), ('12', "Qoraqalpog'iston"), ('7', 'Samarqand')], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('4', '4'), ('2', '2'), ('1', '1'), ('5', '5')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
