# Generated by Django 4.0.3 on 2022-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0015_alter_uylar_viloyat_alter_uylar_xonalar_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('10', 'Surxandaryo'), ('12', "Qoraqalpog'iston"), ('6', 'Buxoro'), ('3', "Farg'ona"), ('1', 'Toshkent Shahar'), ('8', 'Xorazm'), ('11', 'Navoiy'), ('4', 'Andijon'), ('5', 'Namangan'), ('2', 'Toshkent Viloyat'), ('9', 'Qashqadaryo'), ('7', 'Samarqand')], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('1', '1'), ('5', '5'), ('3', '3')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
