# Generated by Django 4.0.3 on 2022-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybor', '0017_alter_uylar_aftoturargox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uylar',
            name='Aftoturargox',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Aftoturargox'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='bolalar_maydonchasi',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Bolalar Maydonchasi'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='internet',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=5, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='kanalizatsiya',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Kanalizatsiya'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='lift',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name='Lift'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='qoriqlash',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=2, max_length=100, verbose_name="Qo'riqlash"),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='video_kuzatuv',
            field=models.CharField(choices=[('1', 'Bor'), ('2', "Yo'q")], default=1, max_length=100, verbose_name='Video Kuzatuv'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='viloyat',
            field=models.CharField(choices=[('3', "Farg'ona"), ('1', 'Toshkent Shahar'), ('8', 'Xorazm'), ('5', 'Namangan'), ('9', 'Qashqadaryo'), ('10', 'Surxandaryo'), ('4', 'Andijon'), ('12', "Qoraqalpog'iston"), ('11', 'Navoiy'), ('6', 'Buxoro'), ('2', 'Toshkent Viloyat'), ('7', 'Samarqand')], default=1, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='uylar',
            name='xonalar_soni',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('4', '4'), ('6', '6'), ('1', '1'), ('5', '5')], default=2, max_length=1, verbose_name='Xonalar Soni'),
        ),
    ]
